version: '2'
services:
 jenkins:
  build: ./jenkins/
  ports:
   - "8080:8080"
  tty: true

 mysql-jira:
  build: ./mysql-jira/
  ports:
   - "3306:3306"
  tty: true

 jira:
  build: ./jira/
  ports: 
   - "8081:8080"
  tty: true
  links:
  - mysql-jira

 nexus:
  build: ./nexus/
  ports: 
   - "8082:8081" 
  tty: true

 tomcat:
  build: ./tomcat/
  ports:
   - "8083:8080"
  tty: true

 zabbix:
  build: ./zabbix/
  ports:
   - "80:80"
  tty: true

 postfix:
  build: ./postfix/
  ports:
   - "25:25"
   - "110:110"
   - "143:143"
   - "465:465"
   - "587:587"
   - "993:993"
   - "995:995"
  tty: true
